### PR TITLE
Add HTTP gateway with conn to GRPC server

### LINKED ISSUE #9: Wire up http gateway
Once the grpc server has any implementation running, the HTTP server can be setup using grpc gateway.

### LINKED ISSUE #16: Add openapi ui and json to http server

### LINKED ISSUE #20: Add back docs
Start with a minimum of package readmes, essential package docs, command readme, and general command docs.

### PR DESCRIPTION
**Pull request by daved**
This adds a minimal/rough example of how to setup a grpc-gateway http server and have it connect to the grpc server. It will soon also include openapi ui endpoints. The commits are bite-sized enough to be useful as a walk-through.

Fixes #9, Fixes #16, Fixes #20

### CODE REVIEW

**Comment by daved** [comment]
The swagui commit is a bit large, but we'll likely discuss the details as we go along.

**Comment by daved** [comment]
This now includes initial backend docs.
Fixes #20

**Comment by daved** [comment]
This now include initial backend docs.
Fixes #20

**Comment by nqthqn** [comment]
@champagneabuelo has voted yes, from meatspace.

**Pull request merged**
