### PR TITLE
back: first services

### LINKED ISSUE #8: Wire up grpc server with empty service implementations
The following interfaces need to be implemented and wired up for the grpc server:
https://github.com/champagneabuelo/openboard/blob/a68d9ac95d18d5d53883dc404dbbe40797a22f4f/back/pb/auth.pb.go#L338-L343
https://github.com/champagneabuelo/openboard/blob/a68d9ac95d18d5d53883dc404dbbe40797a22f4f/back/pb/user.pb.go#L860-L868

The current messages and methods are just for getting things started and we can/should discuss the design soon.

### PR DESCRIPTION
**Pull request by daved**
Fixes #8

### CODE REVIEW

**Comment by daved** [comment]
This is done.
@champagneabuelo Please have a look.

**Comment by daved** [comment]
sigmon is a simple way to handle system signals. It allows us to type {Ctrl-C} to send SIGTERM to the application and have the application take some action. The `Set` method takes a callback which runs when any system signal is received. That callback must take a value representing that system signal in order for the logic to conditionally take different actions. In this case, all signals result in the graceful shutdown of the GRPC server. For more info: https://github.com/codemodus/sigmon

This application is a demonstration of a running GRPC server. It's only purpose for now is as an example of how to add services to the GRPC server. Each commit in this branch takes a small step toward adding one of two services and then wiring them together.

In order to get the "free HTTP" mentioned, we will leverage GRPC-Gateway. An instance of a gateway is created, with the relevant services registered to it. This is then served on it's own separate port. In effect, the GRPC is then a backend to the HTTP backend.

If needed later on, we can add a GraphQL termination point. Though, this would likely mean adding another set of messages which are more highly related/intermingled. Similarly, if HTTP2 is not sufficient for our use case at mitigating transport costs, but GraphQL remains not worth setting up, specific "view messages" could be added as needed. Depending on the circumstances at the time, either of these two systems can be added as a standalone server on it's own port using the GRPC server as a backend, added to some subset of paths (routes) in the then existing HTTP server, or as a standalone server using the HTTP server as a backend. The last option might be dumb, and it might help take care of the whole GraphQL caching issue. I'm not sure; It's late.

**Comment by daved** [comment]
@champagneabuelo I just added a frontend file server. To try it out, run `go run *.go` from `back/cmd/openbsrv` or build as you might any Go app and run the artifact from that same directory.

The front files are currently being served using a relative path, but I'll work out how to run the project from anywhere. It will likely require the usage of some flag or envvar (preferably a flag).  A good test file is http://localhost:4244/css/main.css

**Comment by daved** [comment]
I'll merge this once I get an OK on the temporary front server.

**Comment by champagneabuelo** [comment]
Working on getting in running locally now! Will report back soon.

**Comment by champagneabuelo** [comment]
After running the ```go run *.go``` command, this was the output I got:
```{0   false  false    [] <nil> <nil> <nil> <nil> <nil> {} [] 0}```

**Comment by daved** [comment]
That is a random generated type that I selected to print just to prove that the generated code was working. Did it also give a notice about gracefully stopping the application?

**Pull request merged**
